# Generated by Django 3.2.10 on 2021-12-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_exchange_office', models.CharField(max_length=100, verbose_name=' Обменник')),
                ('rate_given_exchange', models.CharField(max_length=100, verbose_name='Курс отдаю')),
                ('rate_received_exchange', models.CharField(max_length=100, verbose_name='Курс получаю')),
                ('reserve', models.CharField(max_length=100, verbose_name='резерв')),
                ('reviews', models.CharField(max_length=255, verbose_name='Отзывы')),
                ('total_exchanger_given', models.CharField(default=0, max_length=100, verbose_name=' количество обменников отдаю')),
                ('total_exchanger_received', models.CharField(default=0, max_length=100, verbose_name=' количество обменников получаю')),
                ('sum_reserve_given', models.CharField(default=0, max_length=100, verbose_name='суммарный резерв со всех обменников отдаю')),
                ('sum_reserve_received', models.CharField(max_length=100, verbose_name='суммарный резерв со всех обменников получаю')),
            ],
            options={
                'verbose_name': 'Нужные Данных',
                'verbose_name_plural': 'Нужные Данных',
            },
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exchange_office', models.CharField(max_length=100, verbose_name='ID обменного пункта')),
                ('name_exchange_office', models.CharField(max_length=100, verbose_name='Название обменного пункта')),
                ('WMBL', models.CharField(max_length=100)),
                ('reserve', models.CharField(max_length=100, verbose_name='резерв')),
            ],
            options={
                'verbose_name': 'список обменных пунктов',
                'verbose_name_plural': 'список обменных пунктов',
                'unique_together': {('id_exchange_office', 'name_exchange_office', 'WMBL', 'reserve')},
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_given_exchange', models.CharField(max_length=100, verbose_name='Курс отдаю')),
                ('rate_received_exchange', models.CharField(max_length=100, verbose_name='Курс получаю')),
                ('reviews', models.CharField(max_length=255, verbose_name='Отзывы')),
                ('exchanges', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_scraping.exchanges', verbose_name='Обменного пунк')),
            ],
            options={
                'verbose_name': ' список курсов обмена',
                'verbose_name_plural': ' список курсов обмена',
                'unique_together': {('rate_given_exchange', 'rate_received_exchange', 'reviews', 'exchanges')},
            },
        ),
        migrations.CreateModel(
            name='ExchangesRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchanges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_scraping.exchanges', verbose_name='Oбменных пунктов')),
                ('rates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_scraping.rates', verbose_name='Kурс обмена')),
            ],
        ),
    ]
