# Generated by Django 3.2.10 on 2021-12-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_currency', models.CharField(max_length=100, verbose_name='ID валюты')),
                ('name_currency', models.CharField(max_length=100, verbose_name='Название валюты')),
            ],
            options={
                'verbose_name': 'Список валют в формате',
                'verbose_name_plural': 'Списки валют в формате',
            },
        ),
        migrations.CreateModel(
            name='DataSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_exchange_office', models.CharField(max_length=100, verbose_name=' Обменник')),
                ('name_rate_received_exchange', models.CharField(max_length=100, verbose_name='Получаемой валюты')),
                ('name_rate_given_exchange', models.CharField(max_length=100, verbose_name='Отдаваемой валюты')),
                ('rate_given_exchange', models.CharField(max_length=100, verbose_name='Курс отдаю')),
                ('rate_received_exchange', models.CharField(max_length=100, verbose_name='Курс получаю')),
                ('reserve', models.CharField(max_length=100, verbose_name='резерв')),
                ('reviews', models.CharField(max_length=255, verbose_name='Отзывы')),
                ('total_exchanger', models.CharField(default=0, max_length=100, verbose_name=' количество обменников ')),
                ('sum_reserve', models.CharField(default=0, max_length=100, verbose_name='суммарный резерв со всех обменников ')),
            ],
            options={
                'verbose_name': 'Нужные Данных',
                'verbose_name_plural': 'Нужных Данных',
            },
        ),
        migrations.CreateModel(
            name='Exchanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exchange_office', models.CharField(max_length=100, verbose_name='ID обменного пункта')),
                ('name_exchange_office', models.CharField(max_length=100, verbose_name='Название обменного пункта')),
                ('WMBL', models.CharField(max_length=100)),
                ('reserve', models.CharField(max_length=100, verbose_name='резерв')),
            ],
            options={
                'verbose_name': 'Ссписок обменных пунктов',
                'verbose_name_plural': 'Списки обменных пунктов',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rate_received_exchange', models.CharField(max_length=100, verbose_name='Получаемой валюты')),
                ('name_rate_given_exchange', models.CharField(max_length=100, verbose_name='Отдаваемой валюты')),
                ('rate_given_exchange', models.CharField(max_length=100, verbose_name='Курс отдаю')),
                ('rate_received_exchange', models.CharField(max_length=100, verbose_name='Курс получаю')),
                ('reviews', models.CharField(max_length=255, verbose_name='Отзывы')),
                ('exchanges', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_scraping.exchanges', verbose_name='Обменного пунк')),
                ('id_rate_given_exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_given', to='site_scraping.currencies', verbose_name='ID отдаваемой валюты')),
                ('id_rate_received_exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_received', to='site_scraping.currencies', verbose_name='ID пПолучаемой валюты')),
            ],
            options={
                'verbose_name': 'Список курсов обмена',
                'verbose_name_plural': 'Списки курсов обмена',
            },
        ),
    ]
